openapi: 3.0.1
info:
  title: Customer CRUD
  description: Customer CRUD API.
  version: 1.0.0
servers:
- url: /v2
paths:
  /customer:
    get:
      summary: Get Customer
      operationId: getCustomer
      responses:
        200:
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Add a Customer
      operationId: addCustomer
      requestBody:
        description: Customer to be added 
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
        required: true
      responses:
        200:
          description: Customer Added
          content:
            application/json:
              schema:
                type: string
      x-codegen-request-body-name: customer
components:
  schemas:
    Customer:
      type: object
      properties:
        id:
          type: integer
          format: int64
        age:
          type: integer
          format: int64
        registrationDate:
          type: string
          format: date-time
          example: 2017-07-21T17:32:28Z